apiVersion: v1
kind: Service
metadata:
  name: {{template "ennote.name" . }}
  namespace: {{ template "ennote.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "ennote.name" .}}'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ template "ennote.label" .}}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    {{- if .Values.service.labels }}
  {{ toYaml .Values.service.labels | indent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
annotations:
  {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: {{.Values.service.clusterIP}}
  {{- end }}
  ports:
    - port: {{.Values.service.port}}
      name: http
      targetPort: {{ .Values.service.targetPort }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
      {{- end }}
  selector:
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
  type: {{.Values.service.type}}
    {{if eq .Values.service.type "LoadBalancer"}}
    {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
    {{- end }}
    {{if .Values.service.loadBalancerIP}}
  loadBalancerIP: {{.Values.service.loadBalancerIP}}
    {{end}}
    {{end}}